version: '3'

services:
  
  app:
    image: codeeducation/keycloak:11.0.2-fix-translate
    container_name: keycloak-auth-app
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_ADDR=db
      - DB_VENDOR=mysql
      - DB_DATABASE=keycloak_auth
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
    ports:
      - 8080:8080
    depends_on:
      - db
        
  db:
    image: melquiadesrodrigues/mysql:5.7
    container_name: keycloak-auth-db
    restart: always
    tty: true
    volumes:
    - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=keycloak_auth
      - MYSQL_ROOT_PASSWORD=root
    